apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
  labels:
    app: mysqlpod
spec:
  containers:
    - name: mysqlpod
      image: mysql:5.6
      env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: teste123
      ports:
        - containerPort: 3306
